apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  mysql-password: cGFzc3dvcmQ=
  mail-password: bWRzaSBrZnJjIGFieGUgeGRzeg==
  admin-password: YWRtaW4xMjM=
  stock-api-key: Wlo1T1RGU0ExMEtRRjdGTA==
  razorpay-key: cnpwX3Rlc3RfU2l4Qk9oTDViNFFFZ1U=
  razorpay-secret: VnpNQ1ZTandzdmZCdWtmVjlON1VvczEy
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=
